version = 0.1

[default.deploy.parameters]
stack_name = "oauth"
resolve_s3 = true
s3_prefix = "oauth"
profile = "aws"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BetterAuthUrl=\"https://oauth21.vercel.app\" GoogleClientId=\"851793713357-efu64vah4peecto0r4l1vnc9ctlpc043.apps.googleusercontent.com\" FrontendUrl=\"https://oauth21.vercel.app\""
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
