import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { authClient } from '@/lib/auth-client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Separator } from '@/components/ui/separator';
import { Card, CardContent } from '@/components/ui/card';
import { toast } from 'sonner';

type Mode = 'totp' | 'backup';

export const AdminTwoFactor: React.FC = () => {
  const [code, setCode] = useState('');
  const [mode, setMode] = useState<Mode>('totp');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [failedAttempts, setFailedAttempts] = useState(0);
  const navigate = useNavigate();

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!code) return;
    setLoading(true);
    setError(null);

    try {
      if (mode === 'totp') {
        const { error: err } = await authClient.twoFactor.verifyTotp({ code });
        if (err) {
          const errMsg = err.message || 'Invalid 6-digit TOTP token. Check your authenticator app.';
          setError(errMsg);
          toast.error(errMsg);
          const nextFail = failedAttempts + 1;
          setFailedAttempts(nextFail);
          
          if (nextFail >= 3 || err.status === 401 || err.status === 403 || errMsg.toLowerCase().includes('session')) {
            toast.error('Authentication session invalidated. Please re-enter your credentials.');
            setTimeout(() => {
              navigate('/admin/login?error=mfa_failed', { replace: true, viewTransition: true });
            }, 1200);
          }
          return;
        }
      } else {
        const { error: err } = await authClient.twoFactor.verifyBackupCode({ code });
        if (err) {
          const errMsg = err.message || 'Invalid emergency backup key.';
          setError(errMsg);
          toast.error(errMsg);
          const nextFail = failedAttempts + 1;
          setFailedAttempts(nextFail);
          
          if (nextFail >= 3 || err.status === 401 || err.status === 403 || errMsg.toLowerCase().includes('session')) {
            toast.error('Authentication session invalidated. Please re-enter your credentials.');
            setTimeout(() => {
              navigate('/admin/login?error=mfa_failed', { replace: true, viewTransition: true });
            }, 1200);
          }
          return;
        }
      }

      toast.success('Telemetry authorization verified');
      navigate('/admin', { replace: true, viewTransition: true });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Network error validating token';
      setError(msg);
      toast.error(msg);
    } finally {
      setLoading(false);
    }
  };

  const toggleMode = () => {
    setCode('');
    setError(null);
    setMode((m) => (m === 'totp' ? 'backup' : 'totp'));
  };

  const handleBackToLogin = () => {
    navigate('/admin/login', { viewTransition: true });
  };

  return (
    <div className="min-h-screen w-full flex items-center justify-center p-6 sm:p-12 bg-background relative selection:bg-accent selection:text-accent-foreground">
      {/* Subtle telemetry grid */}
      <div 
        className="fixed inset-0 pointer-events-none opacity-[0.02] -z-10"
        style={{
          backgroundImage: `radial-gradient(circle at 1px 1px, currentColor 1px, transparent 0)`,
          backgroundSize: '24px 24px'
        }}
      />

      <div className="w-full max-w-[460px]">
        <Card className="w-full">
          <CardContent className="p-8 sm:p-[34px]">
            <div className="flex items-center gap-3 mb-6">
              <div className="flex h-3.5 gap-0.5 items-center">
                <div className="w-[3px] h-3.5 bg-[#0066B1] -skew-x-12" />
                <div className="w-[3px] h-3.5 bg-[#1C69D4] -skew-x-12" />
                <div className="w-[3px] h-3.5 bg-[#E22718] -skew-x-12" />
              </div>
              <span className="font-mono text-xs uppercase tracking-[0.2em] text-muted-foreground">
                <span className="text-foreground font-medium">SWYRA //</span> M Second Factor
              </span>
            </div>

            <div className="mb-8">
              <h1 className="font-heading text-[34px] leading-[1.2] tracking-[-0.02em] font-normal text-foreground">
                {mode === 'totp' ? 'MFA Validation' : 'Emergency Key'}
              </h1>
              <p className="font-sans text-sm text-muted-foreground mt-2">
                {mode === 'totp'
                  ? 'Input the active 6-digit TOTP key generated by your authenticator.'
                  : 'Input one of your saved emergency single-use backup keys.'}
              </p>
            </div>

            {error && (
              <div className="mb-6 rounded-[16px] border border-destructive/30 bg-destructive/10 p-3.5 font-mono text-xs text-destructive flex items-center gap-2.5 animate-in fade-in zoom-in-95">
                <svg className="size-4 shrink-0 text-destructive" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <span>{error}</span>
              </div>
            )}

            <form onSubmit={handleVerify} className="space-y-[21px]">
              <div className="space-y-1">
                <label className="font-mono text-xs uppercase tracking-wider text-muted-foreground">
                  {mode === 'totp' ? '6-Digit TOTP Token' : 'Emergency Backup Key'}
                </label>
                <Input
                  type="text"
                  inputMode={mode === 'totp' ? 'numeric' : 'text'}
                  autoComplete="one-time-code"
                  placeholder={mode === 'totp' ? '000000' : 'xxxxxxxx-xxxx'}
                  maxLength={mode === 'totp' ? 6 : 20}
                  required
                  value={code}
                  onChange={(e) => {
                    setError(null);
                    setCode(e.target.value.trim());
                  }}
                  disabled={loading}
                  className={mode === 'totp' ? 'text-center font-mono text-xl tracking-[0.3em]' : 'font-mono text-sm'}
                />
              </div>

              <Button type="submit" className="w-full mt-4" disabled={loading || !code}>
                {loading ? 'Validating Token...' : 'Verify Identity'}
              </Button>
            </form>

            <div className="my-[21px] flex items-center gap-4">
              <Separator className="flex-1" />
              <span className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
                ALTERNATE
              </span>
              <Separator className="flex-1" />
            </div>

            <Button
              type="button"
              variant="outline"
              onClick={toggleMode}
              className="w-full"
            >
              {mode === 'totp' ? 'Use Emergency Backup Key' : 'Use Authenticator TOTP App'}
            </Button>

            <div className="mt-6 pt-4 border-t border-border/40 text-center">
              <button
                type="button"
                onClick={handleBackToLogin}
                className="font-mono text-xs text-muted-foreground hover:text-foreground transition-colors inline-flex items-center gap-1.5 cursor-pointer"
              >
                ← Return to Admin Sign In
              </button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};
